### PR TITLE
Update to jsdom 16, remove mutationobserver shim

### PR DESCRIPTION
**Pull request by tstirrat**
jsDOM 16 Has more DOM emulation features

### CODE REVIEW

**Comment by tstirrat** [comment]
Strange. unit tests seemed to work fine, including coverage on local

**Comment by yuchenshi** [comment]
`BigInt` is not defined? What did they pull in in jsdom 16?

**Comment by yuchenshi** [comment]
So the CI just failed with a different error message. If anything, it looks like there is a race condition in the test setup to me. Feel free to investigate if you have more time, or just hold off on jsdom 16 for now.

**Comment by tstirrat** [comment]
Sadly, I don't really want to fix node 8 BigInt with another shim. its not exactly any worse than the mutation observer shim. will leave as is

**Pull request closed without merging**
