### PR TITLE
Support != and not-in queries in Firestore viewer

### PR DESCRIPTION
**Pull request by tanabee**
This PR does != and not-in query supports in Firestore viewer. ( issue: https://github.com/firebase/firebase-tools-ui/issues/412 )

I updated the `firebase-js-sdk` version because it needs `WhereFilterOp` updates.
https://github.com/firebase/firebase-js-sdk/pull/3793

### CODE REVIEW

**Comment by yuchenshi** [comment]
@tanabee Thanks for the PR! Unfortunately, TypeScript isn't too happy about this change. Would you mind looking into [the compilation errors](https://github.com/firebase/firebase-tools-ui/pull/413/checks?check_run_id=1401917247#step:5:18)?

**Comment by tanabee** [comment]
@yuchenshi Thank you for the review!

The error also occurs in the current master branch. Please help me if you have any solutions.

**Comment by tanabee** [comment]
@yuchenshi Thank you for the review! I understand. I'll fix it.

**Comment by tanabee** [comment]
@yuchenshi I fixed the build errors. Do I also need to fix unit test errors? These errors seem to be occurring on the current master branch.

**Comment by yuchenshi** [comment]
@tanabee I've fixed the build / tests in #418 and upgraded `firebase`. Please rebase against latest `master` and drop the changes in `package.json`, `package-lock.json` and `src/components/Firestore/testing/FirestoreTestProviders.tsx`.

**Comment by tanabee** [comment]
@yuchenshi Thank you! I updated.

**Review by yuchenshi — APPROVED** [review]

**Comment by yuchenshi** [comment]
@tanabee @AntonioRdzNav Cheers! This will be included in the next release.

**Comment by tanabee** [comment]
Thank you for your support!

**Pull request merged**
