### PR TITLE
#286: Emulator UI should not connect to 0.0.0.0 for emulators

### PR DESCRIPTION
**Pull request by gautamsingal**
Description:
    - Added check whether info.host is not 0.0.0.0 or ::
    - If it is present, then update the host with localhost else it remains same
    - Pass the new value to hostAndPort

### CODE REVIEW

**Comment by gautamsingal** [comment]
@yuchenshi Will this be good?
`const host =
        info.host === '0.0.0.0' || info.host === '::'
          ? info.host === '0.0.0.0' ? '127.0.0.1' : '::1'
          : info.host;`

**Comment by yuchenshi** [comment]
> `const host = info.host === '0.0.0.0' || info.host === '::' ? info.host === '0.0.0.0' ? '127.0.0.1' : '::1' : info.host;`

That is logically correct, but for let's stay away from chained ternaries for clarity. I suggest:

```js
let host = info.host;
if (host === '0.0.0.0') {
  host = '127.0.0.1';
} else if (host === '::') {
  host = '::1';
}
```

**Comment by gautamsingal** [comment]
@yuchenshi Okay 😁

**Comment by yuchenshi** [comment]
This will be included in the next release. Cheers!

**Comment by gautamsingal** [comment]
Great! Thanks @yuchenshi . Cheers!

**Pull request merged**
